version: '3'

services:
  loki:
    image: grafana/loki:2.5.0
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks:
      - loki
    
  promtail:
    image: grafana/promtail:2.5.0
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - loki
    ports:
      - 9080:9080  
    volumes:
      - "./logs:/logs"
      - "./config.yaml:/etc/promtail/config.yml"

  grafana: 
    image: grafana/grafana:9.0.1
    ports:
      - "3000:3000"
    depends_on: 
      - loki
    networks: 
      - loki
    links:
      - loki    


networks:
  loki: 
    driver: bridge